# Generated by Django 5.1.2 on 2024-12-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
